name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

env:
  OIDC_IAM_ROLE_ARN: ${{ secrets.OIDC_IAM_ROLE_ARN }}
  AWS_REGION: us-west-2

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.OIDC_IAM_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}

    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        check-latest: true

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      id: pnpm-install
      with:
        run_install: |
          - recursive: true
            args: [--no-frozen-lockfile]
          - args: [--global, aws-cdk]

    - name: deploy (cdk)
      working-directory: cdk
      env:
        CI: 1
      run: 
        cdk deploy

    - name: Get URL
      id: get-url
      uses: ./.github/actions/get-stack-output
      with:
        stack-name: react-router-ssr-lambda-stack
        output-key: Output

    - name: Verify HTTP Status
      env:
        URL: ${{ steps.get-url.outputs.output-value }}
      run: |
        CODE=$(curl -w "%{http_code}\n" -o /dev/null -sSL "$URL")
        if [ "$CODE" != "200" ]; then exit 1; fi
